config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: 'about#index'
  get 'libraries', to: 'libraries#index'
  get 'libraries/:id', to: 'libraries#show', as: 'library'
  get 'books', to: 'books#index'
  get 'books/:id', to: 'books#show', as: 'book'
  get 'locations', to: 'locations#index'
  get 'locations/:id', to: 'locations#show', as: 'location'
  get 'librarians', to: 'librarians#index'
  get 'librarians/:id', to: 'librarians#show', as: 'librarian'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.random_collection(size_of_collection)
    number_of_rows_available = count
    random_offset = rand(number_of_rows_available - size_of_collection)
    offset(random_offset).limit(size_of_collection)
  end

  def self.random
    random_collection(1).first
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :libraries_books
  has_many :libraries, through: :libraries_books
  max_paginates_per 8
  validates :title, presence: true
  validates :author, presence: true
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  belongs_to :library
  validates :name, presence: true
  validates :age, numericality: { only_integer: true }
end

app/models/libraries_book.rb
class LibrariesBook < ApplicationRecord
  belongs_to :library
  belongs_to :book
end

app/models/library.rb
# frozen_string_literal: true

class Library < ApplicationRecord
  has_many :libraries_books
  has_many :books, through: :libraries_books
  has_many :librarians
  belongs_to :location
  validates :name, :wifi, presence: true
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_one :library
  validates :address, :coordinates, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.order(:title).page params[:page]
  end

  def show
    @books = Book.includes(:libraries).find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/librarians_controller.rb
# frozen_string_literal: true

class LibrariansController < ApplicationController
  def index
    @librarians = Librarian.all
  end

  def show
    @librarians = Librarian.find(params[:id])
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def show
    @libraries = Library.includes(:librarians, :books).find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @locations = Location.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
  def splitter(location)
    return location.split(',').map(&:to_f)
  end
end

app/views/about/index.html.erb
<div class="container">
The Library List Rails project features four tables with three associations: a one-to-one, a one-to-many, and a many-to-many.

The data is seeded through three different sources:

<ul>
<li>The main source of data is from the City of Winnipeg open data portal which can be found here:</li>

https://data.winnipeg.ca/resource/itub-a6x4.json?$$app_token=swjqemjyTcsrJ7oYJOD5g5Kwg

<li>The names generated for the librarians randomly assigned through the uiNames API.</li>

https://uinames.com/api/?ext&amount=500

<li>Finally, books and their information were generated using the Faker gem for randomized names, genres, and offers.</li>
</ul>
</div>
<div class="container">
<%= image_tag "erd.png", alt: "ERD Diagram" %>
</div>

app/views/books/index.html.erb
<div class="container">
<table class="table table-hover">
<% @books.each do |book| %>
<tr>
<td><%= link_to book.title, book %></td>
<td><%= book.author %></td>
</tr>
<% end %>
</table>

<%= paginate @books %>
</div>

app/views/books/show.html.erb
<h3><%= @books.title %></h3>
<h5><%= @books.author %></h5>
<h6>Genre: <%= @books.genre %></h6>
<% if @books.libraries.empty? %>
<p>There are no libraries with this book :(</p>
<% else %>
<p>This book is in these libraries:</p>

<% @books.libraries.each do |library| %>
  <ul><%= link_to library.name, library %> </ul>
<% end %>
<% end %>

app/views/home/index.html.erb
<p>Welcome to the Library List!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/cosmo/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <%= link_to 'LL', root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'About', about_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Libraries', libraries_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Books', books_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Librarians', librarians_path, :class => "nav-link" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/librarians/index.html.erb
<div class="container">
<table class="table table-hover">
<% @librarians.each do |librarian| %>
  <tr>
    <td><%= link_to librarian.name, librarian %></td>
  <tr>
<% end %>
</table>
</div>

app/views/librarians/show.html.erb
<h3>Librarian Profile</h3>
<p>Name: <%= @librarians.name %></p>
<p>Age: <%= @librarians.age %></p>
<p>Library: <%= link_to @librarians.library.name, @librarians.library %></p>

app/views/libraries/index.html.erb
<div class="container">
<table class="table table-hover">
  <th>Library Name</th>
  <th>Location</th>
  <% @libraries.each do |library| %>
  <tr>
    <td><%= link_to library.name, library %></td>
    <td><%= library.location.address %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/libraries/show.html.erb
<h3><%= @libraries.name %></h3>
<p>There library is located at  <%= link_to @libraries.location.address, @libraries.location %>.</p>
<p>There are <%= @libraries.books.count %> books in this library.</p>

<% @libraries.books.each do |book| %>
  <ul><%= link_to book.title, book %> </ul>
<% end %>

<p>There are <%= @libraries.librarians.count %> librarians who work here.</p>

<% @libraries.librarians.each do |librarian| %>
  <ul><%= link_to librarian.name, librarian %> </ul>
<% end %>

app/views/locations/index.html.erb
<% @locations.each do |location| %>
<h3><%= link_to location.address, location %></h3>
<% end %>

app/views/locations/show.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />

<h3><%= @locations.address %></h3>

<p>The library at this location is <%= link_to @locations.library.name, @locations.library %>.</p>

<% array = splitter(@locations.coordinates) %>
<% lat = array[0] %>
<% long = array[1] %>


<div id='map' style='width: 400px; height: 300px;'></div>
<script>
  var lat1 = <%= lat %>
  var long1 = <%= long %>
  mapboxgl.accessToken = 'pk.eyJ1IjoibWtyZW5hdWQiLCJhIjoiY2s2MHU3NXN2MGJ4bTNqcGs4MWZyejN4dyJ9.P1503rPR03lDpziXHVQt6Q';
  var map = new mapboxgl.Map({
    container: 'map',
    center: [long1, lat1],
    zoom: 15,
    style: 'mapbox://styles/mapbox/streets-v11'
  });
</script>